apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-kube-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/NeRd-StEyN/K8s.git'
    targetRevision: HEAD
    path: deployment-gitops/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
